### ISSUE TITLE
Flex recipes failing for Symfony 4.2.5 

### ISSUE THREAD

**Issue by rkmourya** [sphereio/commercetools-php-symfony#69]
I am trying to use this bundle with Symfony 4.2.5. I followed the steps mentioned in the readme.
```sh
composer config extra.symfony.allow-contrib true
composer require commercetools/symfony-bundle
```

But no bundle got added to config/bundles.php
Also it seems yml files are no updated for required config

If I am manually adding below entries in config/bundles.php
```php
    Commercetools\Symfony\CtpBundle\CtpBundle::class => ['all' => true],
    Commercetools\Symfony\CartBundle\CartBundle::class => ['all' => true],
```

I am getting below error.
In CommercetoolsExtension.php line 32: Notice: Undefined offset: 0

I tried making below entries in config/config.yml, but nothing helping
```yml
commercetools:
  credentials:
    client_id: "%commercetools.client_id%"
    client_secret: "%commercetools.client_secret%"
    project: "%commercetools.project%"
    scope: "%commercetools.scope%"
    api_url: "%commercetools.api_url%"
    oauth_url: "%commercetools.oauth_url%"
```

**Comment by nikossvnk** [comment]
There is still an issue with the recipe and is not yet officialy published, which explains why you didn't get the initial configuration. For now, you can do it manually by edititng:

file `config/packages/commercetools.yaml`
```
commercetools:
    api:
        default_client: 'default'
        clients:
            default:
                client_id: '%env(CTP_CLIENT_ID)%'
                client_secret: '%env(CTP_CLIENT_SECRET)%'
                project: '%env(CTP_PROJECT_KEY)%'
                scope: '%env(CTP_SCOPES)%'
                oauth_url: '%env(CTP_AUTH_URL)%'
                api_url: '%env(CTP_API_URL)%'
```

file `config/bundles.php` for minimun enabled bundles:
```
    Commercetools\Symfony\CtpBundle\CtpBundle::class => ['all' => true],
    Commercetools\Symfony\SetupBundle\SetupBundle::class => ['all' => true],
```
or you may enable all bundles:
```
    Commercetools\Symfony\CtpBundle\CtpBundle::class => ['all' => true],
    Commercetools\Symfony\CartBundle\CartBundle::class => ['all' => true],
    Commercetools\Symfony\CustomerBundle\CustomerBundle::class => ['all' => true],
    Commercetools\Symfony\ReviewBundle\ReviewBundle::class => ['all' => true],
    Commercetools\Symfony\CatalogBundle\CatalogBundle::class => ['all' => true],
    Commercetools\Symfony\ShoppingListBundle\ShoppingListBundle::class => ['all' => true],
    Commercetools\Symfony\SetupBundle\SetupBundle::class => ['all' => true],
    Commercetools\Symfony\StateBundle\StateBundle::class => ['all' => true],
```

file `.env` (you need to replace your credentials ofcource)
```
CTP_CLIENT_ID=<your client id>
CTP_CLIENT_SECRET=<your client secret>
CTP_PROJECT_KEY=<your project id>
CTP_AUTH_URL=https://auth.commercetools.com or https://auth.commercetools.co
CTP_API_URL=https://api.commercetools.com or https://api.commercetools.co
CTP_SCOPES=<your desired scopes>
```

Optionally, in case you want to use commercetools for the user login system you can edit file `config/packages/security.yaml` as:

```
security:
    providers:
        ctp:
            id: Commercetools\Symfony\CustomerBundle\Security\User\UserProvider
    access_control:
        - { path: /user/, roles: ROLE_USER }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Commercetools\Symfony\CustomerBundle\Security\User\User: plaintext
    firewalls:
        main:
            anonymous: ~
            commercetools-login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
```

Apologies for the inconvinience

**Comment by rkmourya** [comment]
Thanks for the configuration.

Other than that there seems to be issue with dependencies of the project. I got below error now.

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
  The service "commercetools.profiler_controller" has a dependency on a non-existent service "templating".

I resolved this by manually including templating
```sh
composer require symfony/templating
```
and adding below to config/packages/framework.yaml
```yml
framework:
    templating:
        engines:
            - twig
```

Now running below command
```sh
php bin/console commercetools:project-info
```
throws below error.

```
console.ERROR: Error thrown while running command "commercetools:project-info". Message: "Error completing request" {"exception":"[object] (Commercetools\\Core\\Error\\ApiException(code: 0): Error completing request at C:\\projects\\commercetools-gateway\\vendor\\commercetools\\php-sdk\\src\\Core\\Error\\ApiException.php:50)","command":"commercetools:project-info","message":"Error completing request"} []
console.DEBUG: Command "commercetools:project-info" exited with code "1" {"command":"commercetools:project-info","code":1} []
```
There is no proper error code to trace this error.
